parameters:
  environment:
    type: string
  nodeVersion:
    type: string

jobs:
- job: BuildAndTest
  pool:
    name: SelfHostedAgentPool-vm-TOOLSYUL000
    demands:
      - agent.name -equals vm-TOOLSYUL000
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: ${{ parameters.nodeVersion }}
    displayName: 'Install Node.js'
  - script: npm install
    displayName: 'Install dependencies'
  - script: npm test
    displayName: 'Run tests'
  - script: npm run build
    displayName: 'Build project'
  - script: echo "Deploying to ${{ parameters.environment }}"
    displayName: 'Print environment'
