parameters:
  environment:
    type: string

jobs:
- job: TerraformApply
  pool:
    name: SelfHostedAgentPool-vm-TOOLSYUL000
    demands:
      - agent.name -equals vm-TOOLSYUL000
  steps:
  - checkout: templateRepo
    displayName: 'Checkout GitHub repository'
  - script: |
      export ARM_CLIENT_ID=$(ARM_CLIENT_ID)
      export ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
      export ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
      export ARM_TENANT_ID=$(ARM_TENANT_ID)
      terraform init
    displayName: 'Initialize Terraform'
  - script: terraform plan -out=tfplan
    displayName: 'Plan Terraform changes'
  - script: terraform apply -auto-approve tfplan
    displayName: 'Apply Terraform changes'
  - script: echo "Deployed to ${{ parameters.environment }}"
    displayName: 'Print environment'
