parameters:
  environment:
    type: string
  nodeVersion:  # Este parámetro ya no es necesario, pero lo mantenemos por compatibilidad
    type: string

jobs:
- job: TerraformApply
  pool:
    name: SelfHostedAgentPool-vm-TOOLSYUL000
    demands:
      - agent.name -equals vm-TOOLSYUL000
  steps:
  - checkout: git://Yu1ia777/dev-DEVCUApp-02
    displayName: 'Checkout GitHub repository'
  - script: terraform init
    displayName: 'Initialize Terraform'
  - script: terraform plan -out=tfplan
    displayName: 'Plan Terraform changes'
  - script: terraform apply -auto-approve tfplan
    displayName: 'Apply Terraform changes'
  - script: echo "Deployed to ${{ parameters.environment }}"
    displayName: 'Print environment'
